mvc/Models/ErrorViewModel.cs
using System;

namespace mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

mvc/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using mvc.Models;

namespace mvc.Controllers
{
    public class EventoController : Controller
    {
        private readonly DB _dbInterno;

        public EventoController(DB dbViaParametro)
        {
            _dbInterno = dbViaParametro;
        }

        //http://localhost:5000/evento
        public IActionResult Index()
        {
            var listaEventos = _dbInterno.Eventos.ToList();

            return View(listaEventos);
        }

        //http://localhost:5000/evento/novo
        public IActionResult Novo()
        {
            var eventoDTO = new EventoDTO();

            return View("Cadastro", eventoDTO);
        }

        //http://localhost:5000/evento/editar/{id}
        public IActionResult Editar(int id)
        {
            var evento = _dbInterno.Eventos.SingleOrDefault(e => e.Id == id);

            var eventoDTO = new EventoDTO
            {
                Id = evento.Id,
                Titulo = evento.Titulo,
                Data = evento.Data
            };

            return View("Cadastro", eventoDTO);
        }

        [HttpPost]
        public IActionResult Salvar(EventoDTO eventoFormulario)
        {
            if (eventoFormulario.Id == 0)
            {
                //Registro novo
                var eventoBD = new Evento();

                eventoBD.Titulo = eventoFormulario.Titulo;
                eventoBD.Data = eventoFormulario.Data;

                _dbInterno.Add(eventoBD);
            }
            else
            {
                //Registro atualizado
                var eventoBD = _dbInterno.Eventos.SingleOrDefault(e => e.Id == eventoFormulario.Id);

                eventoBD.Titulo = eventoFormulario.Titulo;
                eventoBD.Data = eventoFormulario.Data;

                _dbInterno.Update(eventoBD);
            }

            _dbInterno.SaveChanges();

            return RedirectToAction("Index");
        }

        //http://localhost:5000/evento/apagar/{id}
        public IActionResult Apagar(int id)
        {
            var evento = _dbInterno.Eventos.SingleOrDefault(e => e.Id == id);

            _dbInterno.Remove(evento);

            _dbInterno.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc.Models;

namespace mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        //http://localhost:5000/home/index
        public IActionResult Index()
        {
            return View();
        }

        //http://localhost:5000/home/privacy
        public IActionResult Privacy()
        {
            return View();
        }

        //http://localhost:5000/home/help
        public IActionResult Help()
        {
            ViewData["horaAtual"] = DateTime.Now.ToString("HH:mm:ss");
            
            return View();
        }

        //http://localhost:5000/home/error
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mvc/Views/Evento/Cadastro.cshtml
@model EventoDTO
@{
    ViewData["Title"] = "Eventos";
}

<div class="text-center">
    <h1 class="display-4">Cadastro</h1>
</div>

<form asp-action="Salvar" method="post">
    
    <label asp-for="Id"></label>
    <input asp-for="Id" readonly />

    <label asp-for="Titulo"></label>
    <input asp-for="Titulo" />

    <label asp-for="Data"></label>
    <input asp-for="Data" />

    <button type="submit">Salvar</button>
</form>

mvc/Views/Evento/Index.cshtml
@using data
@model List<Evento>
@{
    ViewData["Title"] = "Eventos";
}

<a asp-controller="Evento" asp-action="Novo">
    <button class="btn btn-primary">Novo</button>
</a>

<table>
    <tr>
        <th>Id</th>
        <th>Título</th>
        <th>Cancelado</th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var evento in Model)
    {
        <tr>
            <td>@evento.Id</td>
            <td>@evento.Titulo</td>
            <td>@evento.Cancelado</td>
            <td>
                <a asp-controller="Evento" asp-action="Editar" asp-route-id=@evento.Id>
                    <button class="btn btn-secondary">Editar</button>
                </a>
            </td>
            <td>
                <a asp-controller="Evento" asp-action="Apagar" asp-route-id=@evento.Id>
                    <button class="btn btn-danger">Apagar</button>
                </a>
            </td>
        </tr>
    }
</table>

mvc/Views/Home/Help.cshtml
@{
    ViewData["Title"] = "Help";
}

<div class="text-center">
    <h1 class="display-4">Página de ajuda</h1>
    <p>Para mais documentações, consulte <a href="https://ajuda.com">nosso site de ajuda</a>.</p>
    <strong>@ViewData["horaAtual"]</strong>
</div>

mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div class="text-center">
    <h1 class="display-4">Bem-vindo!</h1>
    <h2>Sub-título</h2>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvc/Views/Home/help.cshtml
@{
    ViewData["Title"] = "help";
}

<div class="text-center">
    <h1 class="display-4">Pagina de Ajuda</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Evento" asp-action="Index">Eventos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>